name: "Release"

on:
  release:
    types:
      - "published"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      discussions: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/askoheat"
          zip askoheat.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda" # v2.2.1
        with:
          files: ${{ github.workspace }}/custom_components/askoheat/askoheat.zip
